server:
  port: 8082

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postsDB
    username: root
    password: pass
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

feign:
  image-loader-service:
    url: localhost:8085/image

logging.level.org.springframework.web: INFO

