server:
  port: 8082

spring:
  application:
    name:
      post-service
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postsDB
    username: root
    password: pass
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf
  life-time: 1800000

feign:
  image-loader-service:
    url: localhost:8086/image
  comments-api-service:
    url: localhost:8084/comments

logging.level.org.springframework.web: INFO

